# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanarino', '0005_auto_20190310_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='motif',
            field=models.CharField(default='未分类', max_length=14),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='无题', max_length=14),
        ),
    ]
