# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanarino', '0007_article_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motif',
        ),
    ]
