# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanarino', '0008_delete_motif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='无题', max_length=14)),
                ('imgurl', models.TextField(max_length=64)),
                ('imglen', models.CharField(max_length=2)),
                ('motif', models.CharField(default='未分类', max_length=14)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
